spring:
  application:
    name: temp
  profiles:
    active: prod
server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: local
    import: secret/application-local.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import: secret/application-prod.yml